[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "functions-build"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[functions]
  directory = "functions-build"

