[build]
  functions = "functions"
  command = "npm install && npm run build"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[functions]
  directory = "functions"
